[package]
name = "sem-el"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.95"
arrow-array = "53.3.0"
arrow-schema = "53.3.0"
emacs = "0.19.0"
futures-util = "0.3.31"
lancedb = "0.15.0"
tokio = "1.43.0"
