[package]
name = "sem-el"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.95"
bincode = "1.3.3"
emacs = "0.19.0"
ndarray = { version = "0.16.1", features = ["serde"] }
sha256 = "1.5.0"
